## About the Dataset

The table has one row for each product and several columns.

<ul>
    <li><b>OrderID</b>: A unique identifier for each order</li>
    <li><b>Product</b>: The name of the product purchased</li>
    <li><b>Category</b>: The category to which the product belongs (e.g., Electronics, Furniture, Stationery)</li>
    <li><b>Quantity</b>: The number of units purchased for that product</li>
    <li><b>Price</b>: The price per unit of the product</li>
    <li><b>Total</b>: The total cost for the product (calculated as Quantity × Price)</li>
    <li><b>OrderDate</b>: The date when the order was placed</li>
    <li><b>CustomerCity</b>: The city where the customer resides</li>
    
</ul>

You can see the dataset here:

<font size="1">
<table style="font-size:medium; border:1px solid black; border-collapse:collapse;">
  <tr>
    <th>OrderID</th>
    <th>Product</th>
    <th>Category</th>
    <th>Quantity</th>
    <th>Price</th>
    <th>Total</th>
    <th>OrderDate</th>
    <th>CustomerCity</th>
  </tr>
  <tr>
    <td>1</td>
    <td>Laptop</td>
    <td>Electronics</td>
    <td>2</td>
    <td>800</td>
    <td>1600</td>
    <td>2022-01-10</td>
    <td>New York</td>
  </tr>
  <tr>
    <td>2</td>
    <td>Smartphone</td>
    <td>Electronics</td>
    <td>3</td>
    <td>600</td>
    <td>1800</td>
    <td>2022-02-15</td>
    <td>Los Angeles</td>
  </tr>
  <tr>
    <td>3</td>
    <td>Desk Chair</td>
    <td>Furniture</td>
    <td>5</td>
    <td>150</td>
    <td>750</td>
    <td>2022-03-12</td>
    <td>Chicago</td>
  </tr>
  <tr>
    <td>4</td>
    <td>Notebook</td>
    <td>Stationery</td>
    <td>10</td>
    <td>2</td>
    <td>20</td>
    <td>2022-04-05</td>
    <td>Houston</td>
  </tr>
  <tr>
    <td>5</td>
    <td>Monitor</td>
    <td>Electronics</td>
    <td>1</td>
    <td>300</td>
    <td>300</td>
    <td>2022-05-21</td>
    <td>Miami</td>
  </tr>
</table>
</font>

In [1]:
# Dependency needed to install file 
%pip install xlrd openpyxl

Requirement already satisfied: xlrd in c:\anaconda3\lib\site-packages (2.0.1)
Requirement already satisfied: openpyxl in c:\anaconda3\lib\site-packages (3.0.9)
Requirement already satisfied: et-xmlfile in c:\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Import required library
import pandas as pd

In [4]:
filename = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/LXjSAttmoxJfEG6il1Bqfw/Product-sales.csv'
df = pd.read_csv(filename)

In [5]:
# Print first five rows of the dataframe
df.head()

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
0,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
1,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
2,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
3,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
4,5,Monitor,Electronics,1,300,300,2022-05-21,Miami

In [6]:
xlsx_path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n9LOuKI9SlUa1b5zkaCMeg/Product-sales.xlsx'
df = pd.read_excel(xlsx_path)
df.head()

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
0,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
1,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
2,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
3,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
4,5,Monitor,Electronics,1,300,300,2022-05-21,Miami

In [7]:
# Access to the column Length
x = df[['Quantity']]
x

   Quantity
0         2
1         3
2         5
3        10
4         1

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/CHIJ1eh6tYUzFsmgQIuCSA/1.PNG" width="1150">

## Viewing Data and Accessing Data

In [9]:
# Get the column as a series
x = df['Product']
x

0        Laptop
1    Smartphone
2    Desk Chair
3      Notebook
4       Monitor
Name: Product, dtype: object

In [10]:
# Get the column as a dataframe
x = df[['Quantity']]
type(x)

pandas.core.frame.DataFrame

In [11]:
# Access to multiple columns
y = df[['Product','Category', 'Quantity']]
y

      Product     Category  Quantity
0      Laptop  Electronics         2
1  Smartphone  Electronics         3
2  Desk Chair    Furniture         5
3    Notebook   Stationery        10
4     Monitor  Electronics         1

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/BiDzVOrMQbianIz9DMum7A/2.PNG" width="1100">

In [12]:
# Access the value on the first row and the first column
df.iloc[0, 0]

1

In [13]:
# Access the value on the second row and the first column
df.iloc[1,0]

2

In [14]:
# Access the value on the first row and the third column
df.iloc[0,2]

'Electronics'

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/npw0rMu2hutg8MdOz4t_Kw/3.PNG" width="750">

In [15]:
# Access the column using the name
df.loc[0, 'Product']

'Laptop'

In [16]:
# Access the column using the name
df.loc[1, 'Product']

'Smartphone'

In [17]:
# Slicing the dataframe
df.iloc[0:2, 0:3]

   OrderID     Product     Category
0        1      Laptop  Electronics
1        2  Smartphone  Electronics

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/88vCcZQ8N4W_R7WyKoqoAA/6.PNG" width="750">

## Quiz on DataFrame

Use a variable <code>q</code> to store the column <b>Price</b> as a dataframe

In [18]:
df.head()

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
0,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
1,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
2,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
3,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
4,5,Monitor,Electronics,1,300,300,2022-05-21,Miami

In [21]:
q = df[['Price']]
q

   Price
0    800
1    600
2    150
3      2
4    300

Assign the variable <code>q</code> to the dataframe that is made up of the column <b>Product</b> and <b>Category</b>:

In [22]:
q = df[['Product', 'Category']]
q

      Product     Category
0      Laptop  Electronics
1  Smartphone  Electronics
2  Desk Chair    Furniture
3    Notebook   Stationery
4     Monitor  Electronics

Access the 2nd row and the 3rd column of df:

In [28]:
df.iloc[1, 2]

'Electronics'

Use the following list to convert the dataframe index <code>df</code> to characters and assign it to <code>df_new</code>; find the element corresponding to the row index <code>a</code> and column  <code>'CustomerCity'</code>. Then select the rows <code>a</code> through <code>d</code> for the column  <code>'CustomerCity'</code>

In [29]:
new_index=['a','b','c','d','e']
new_index

['a', 'b', 'c', 'd', 'e']

In [31]:
df_new=df
df_new.index=new_index
df_new.loc['a', 'CustomerCity']
df_new.loc['a':'d', 'CustomerCity']

a       New York
b    Los Angeles
c        Chicago
d        Houston
Name: CustomerCity, dtype: object